Repository AY2223S2-CS2113-F10-2/tp, pull requests merged in 2023-03, with the labels that each got.

#25 PR for matrix multiplication
  src/main/java/seedu/badMaths/matrix/Calculate.java
  src/main/java/seedu/badMaths/matrix/Shape.java
  src/main/java/seedu/badMaths/matrix/Tensor.java
  src/main/java/seedu/badMaths/matrix/Tensor2D.java
  src/test/java/seedu/badMaths/CalculateTest.java
Labels: priority.High

#93 make note more OOP
  src/main/java/seedu/badMaths/BadMaths.java
  src/main/java/seedu/badMaths/Command.java
  src/main/java/seedu/badMaths/Note.java
  src/main/java/seedu/badMaths/NotePriority.java
  src/main/java/seedu/badMaths/Notes.java
  src/main/java/seedu/badMaths/NotesList.java
  src/main/java/seedu/badMaths/Storage.java
  src/main/java/seedu/badMaths/ui/Ui.java
Labels: type.Enhancement, priority.Medium

#96 Add User guide description for Notes.java functionalities
  docs/UserGuide.md
Labels: priority.Medium

#98 Add Sequence Diagram for Developer Guide for Notes.java
  docs/DeveloperGuide.md
  docs/Notes.puml
  docs/img.png
Labels: priority.High

#106 Add UG for the matrix part
  docs/UserGuide.md
  src/test/java/seedu/badMaths/matrix/CalculateTest.java
Labels: priority.High

#116 Update UG
  docs/UserGuide.md
Labels: priority.High

#127 Add JUnit test for Execute, Parser class
  src/test/java/seedu/badMaths/matrix/ExecuteTest.java
  src/test/java/seedu/badMaths/matrix/ParserTest.java
  trigoGraphAnalyser.log
Labels: priority.High
